### ISSUE TITLE
Fixing warning leads to too long line

### ISSUE THREAD

**Issue by ghost** [cphyc/fortran-linter#11]
Hi,

  Suppose there is the following code

```
Program main
  
  integer :: a1, a2,a3,a4,a5,a6,a7,a8,a9,a10000000000000000, a2222222222222222,a333333333333333333,a2222222222222222222, b23,b33

  write (*,*) "Hello World"
End program
```

  `--syntax-only` in 1.0.9 will indicate missing space after punctuation. After `-i`, the new line will exceed the 132 character limit. It may or may not cause a problem. In this case, `gfortran` is OK. In some other cases, I got issue.

  Is that possible to add some auto change line `&` after certain limit? Thanks

**Comment by cphyc** [comment]
I just tested and the code behaves as expected, i.e. it transforms your code into
```fortran
Program main

     integer :: a1, a2, a3, a4, a5, a6, a7, a8, a9, a10000000000000000, a2222222222222222, a333333333333333333, a2222222222222222222, b23, b33

     write (*,*) "Hello World"
End program
```
Note the spacing around `,`.

Unfortunately, I never implemented long-line splitting, which is why the line is now over the character limit. This is a tad difficult for the following (non-exhaustive) reasons, which is why, for now, I haven't tried implementing and leave it to the user's discretion.

- All the other rules work at the line level, while line splitting by essence would create new lines. This makes it more complex (but not impossible) to ensure that the code is idempotent. 
- Lines cannot be split at arbitrary locations. For example, they cannot be split in the middle of a string, so one would need to detect strings and split before/after it. 
- Math operator are commonly placed at the beginning of their line (i.e. `x = 1 & <NEWLINE>+ 1` rather than `x = 1 +&<NEWLINE> 1`, so the line split should happen at the last location right before a math operator. This sounds like it would require a Fortran parser to properly handle all the use cases.

If you feel like trying, I would be happy to review it, noting it should be able to handle the following cases:
```fortran
    ! How is this even supposed to be split ?!
    my_file_name = "this is a very long string which will eventually be longer than the allowed limit. The question is, where should it be split automatically? This case in particular is tricky, since there is no way to just insert a `&\n` anywhere to make all lines below the max line length"
    
    ! Now consider this example
    x = 1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1
    ! Need to be expanded *first* into
    x = 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1
    ! and* then* split as follows
    x = 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 &
     + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 &
     + 1
    ! Note that it is common usage to put the math operator at the beginning of their line (see https://softwareengineering.stackexchange.com/questions/160522/should-i-put-newlines-before-or-after-binary-operators).
```
